function out = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 13-Jan-2013 12:40:20

DELIMITER = ',';
HEADERLINES = 4;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);
out = newData1.data;
% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
end